language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

script:
  - vendor/bin/phpcs -s --standard=phpcs.ruleset.xml .
  - vendor/bin/phpunit
